FROM ubuntu

WORKDIR /EPDCBot

# Install Python and pip
RUN apt update
RUN apt install -y python3 python3-pip

# Install build-essential and libpq-dev for psycopg2
RUN apt install -y build-essential libpq-dev

# Copy requirements.txt and install Python dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy the rest of your bot's code
COPY EPDCBot .

CMD ["python3", "bot.py"]