FROM ubuntu

WORKDIR /EPDCBot

# Setup Python.
RUN apt update
RUN apt install -y python3 python3-pip

# Install pre-reqs for psycopg2.
RUN apt install -y build-essential libpq-dev

# Install pip dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy the bot over.
COPY EPDCBot .

# Sleep so postgres can spool.
CMD python3 bot.py